### ISSUE TITLE
how to do so reuseport?

### ISSUE THREAD

**Issue by sprappcom** [HFQR/xitca-web#1037]
as titled

**Comment by fakeshadow** [comment]
There is https://docs.rs/xitca-web/latest/xitca_web/struct.HttpServer.html#method.listen if you use `xitca-web`. If you are using low level crates there is also https://docs.rs/xitca-server/0.3.0/xitca_server/struct.Builder.html#method.listen if you use `xitca-server`.
Both of them accept `std::net::TcpListener` type
