### ISSUE TITLE
Consider removing ServiceFactoryObject trait

### ISSUE THREAD

**Issue by aliemjay** [HFQR/xitca-web#198]
It's pointless with the introduction of `BuildService` trait. Maybe we can replace it with a proper definition for `BoxedBuildService`:
```rust
struct BoxedBuildService<Arg, Svc, InitErr>(Box<dyn BuildService<Arg, Service=Svc, Error = InitError>>);
```

**Comment by fakeshadow** [comment]
In fact there is `BuildServiceExt::boxed_future` which does the boxing of output Future.
