### ISSUE TITLE
Experiments with borrowed Query and Path extractors

### ISSUE THREAD

**Issue by aliemjay** [HFQR/xitca-web#202]
```suggestion
impl<'a, 'r, S, T> FromRequest<'a, WebRequest<'r, S>> for Query<T>
where
    S: 'static,
    T: Universe,
    T: Deserialize<'a>,
{
    type Type<'b> = Query<T::Type<'b>>;
```

Where `Universe` is the infamous trait:
```rust
trait Universe {
    type Type<'a>: 'a;
}
```

But this requires every type to be deserialized to impl Universe; an ergonomic hurdle but mybe overcome by a homebrew derive(XitcaDeserialize) that implements both serde::Deserialize and Universe and should also be applicable to Path extractor.

_Originally posted by @aliemjay in https://github.com/HFQR/xitca-web/pull/201#discussion_r862337881_

**Comment by fakeshadow** [comment]
Yea it can be added to codegen crate. 
I think we can offer two version of the Query as Owned and Borrowed so people don't want codegen could choose the owned one.

**Comment by fakeshadow** [comment]
`Lazy<Extractor>` has been added to enable zero copy deserialization. They are not clean extractor type but it works now. We can revisit true zero copy extractor later when time comes.
