### ISSUE TITLE
how to used?

### ISSUE THREAD

**Issue by xtuyaowu** [HFQR/xitca-web#283]
Thanks for contributing such a good project, there are a few questions to ask.
1、How to start the http and websoket server.
2、whether there is a filter function to do security verification, etc.

**Comment by fakeshadow** [comment]
1. You can take a look at [examples](https://github.com/HFQR/xitca-web/tree/main/examples). Most of them are http focus and only the websocket example is high level web application.
2. xitca-http and xitca-web support middleware anywhere. You can add middleware to TcpStream/Request/WebRequest layers so I would say yes. Depending on what your goal is you can control your workflow at any level you would like to.

**Comment by xtuyaowu** [comment]
Thanks for such a quick reply, just checked the example, another question：
how to supporting both http and websoket?

thanks again！

**Comment by fakeshadow** [comment]
https://github.com/HFQR/xitca-web/blob/699f67edba491894d57cf5ae24b7b60abfbd9d7d/examples/websocket.rs#L49
websocket is on top of http in xitca-web. You can try to handle websocket anywhere you get hold of a `Request` or `WebRequest` type. In other word you can try to treat any http traffic as websocket if you like. They would fail to do websocket handshake if they are not a websocket request though.

**Comment by xtuyaowu** [comment]
thanks again！
