### ISSUE TITLE
Where is the document?

### ISSUE THREAD

**Issue by amirhossein-fzl** [HFQR/xitca-web#323]
Where is the document?

**Comment by fakeshadow** [comment]
You can use cargo-doc to generate documentation. See this link on how to use it:
https://doc.rust-lang.org/cargo/commands/cargo-doc.html

That said the doc coverage is still poor due to no stable API offered.

**Comment by amirhossein-fzl** [comment]
> You can use cargo-doc to generate documentation. See this link on how to use it: https://doc.rust-lang.org/cargo/commands/cargo-doc.html
> 
> That said the doc coverage is still poor due to no stable API offered.

At least you wrote how to install and use it.

@fakeshadow

**Comment by fakeshadow** [comment]
> At least you wrote how to install and use it.

This is an experimental project (for now) and if you don't know how you should consider avoid this library.
 It has regular break changes without changelog (no change is not meant to be long term) and if you don't have a good knowledge of Rust nor willing to looking into the source it would be a nightmare to work with.

That said you can take a look at the [examples](https://github.com/HFQR/xitca-web/tree/main/examples) if you still decide to try it.

**Comment by fakeshadow** [comment]
available on docs.rs
