### ISSUE TITLE
xitca-postgres & diesel-async

### ISSUE THREAD

**Issue by godofdream** [HFQR/xitca-web#621]
I like the postgres implementation.
Would It make sense to re-use the diesel query-builder like diesel-async does?

**Comment by fakeshadow** [comment]
Thanks for making an issue. Indeed it would be better to have a high level ORM on top of xitca-postgres.
It should be possible to plug in diesel-async(or something like it) api to xitca-postgres as latter is more or less a tokio-posgres fork with almost identical api.
That said the driver is still a work in progress and lacking some important features like transactions/portal/cancel query etc. So right now an ORM implementation could be left with some major blank impls with no actual functionality. I personally would expect no progress until the driver is at least feature comparable to tokio-postgres(which is actively being worked on)

**Comment by godofdream** [comment]
Ok, I'm looking forward to the feature compatible xitca-postgres.
As long as the api is mostly identical diesel-async could get a feature switch to use xitca-postgres.
Do you want to keep this Issue as reminder?

**Comment by fakeshadow** [comment]
> Do you want to keep this Issue as reminder?

Yes let's keep it open.

**Comment by fakeshadow** [comment]
`xitca-postgres` has almost achieve feature parity with `tokio-postgres` lately and I have started looking into integration with `diesel-async`.

Initial work can be found [here](https://github.com/fakeshadow/diesel_async/tree/xitca) where `tokio-postgres` is replaced with `xitca-postgres` as underlying pg client. When this fork is properly tested and optimized I'll look into making it a standalone crate as an extension of `diesel-async`

**Comment by fakeshadow** [comment]
Future development will happen
