### ISSUE TITLE
How to set multiple headers with same name?

### ISSUE THREAD

**Issue by je3f0o** [HFQR/xitca-web#916]
Hello,

I tried to find information about how to set multiple headers with same key.
```rs
pub async fn zzz(ctx: WebContext<'_>) -> Result<WebResponse, Error> {
  let mut res = ctx.into_response(ResponseBody::empty());
  let headers = res.headers_mut();

  let keys = vec!["access", "refresh"];
  for key in keys {
    let mut cookie = Cookie::new(format!("{key}_key"), "abc");
    let lifetime = 5;
    let t = OffsetDateTime::now_utc() + Duration::from_secs(lifetime);
    cookie.set_path("/");
    cookie.set_expires(t);
    cookie.set_http_only(true);
    headers.append(SET_COOKIE, HeaderValue::from_str(&cookie.to_string())?);
  }
  println!("HEADERS: {headers:?}");
  return Ok(res)
}
```

Output has single `set-cookie` header values concatenated with `, `:
```
HTTP/1.1 200 OK
set-cookie: access_key=abc; HttpOnly; Secure; Path=/; Max-Age=5, refresh_key=abc; HttpOnly; Secure; Path=/; Max-Age=5
...
```

**Comment by fakeshadow** [comment]
Multiple header value is represented in the form of  `<field name>: <field value 1>, <field value 2>, ...`
Comma is standard separator of multiple values of a single header and you can reference it here with [RFC9110](https://datatracker.ietf.org/doc/html/rfc9110#name-field-order)

It also point out the edge case of `set-cookie` header and client side should be able to handle this case and generate multiple header value by split the comma.

**Comment by fakeshadow** [comment]
I'm open to handle this edge case server side if it's a necessary special case (if popular clients don't want to or can't handle the separation). Otherwise I personally would prefer following the http/1.1 spec whenever possible.

**Comment by je3f0o** [comment]
But Chrome doesnt read cookies correctly. It's all malformed. First cookie with last cookie's exprire time in:
```
MacOS Chrome
Version 120.0.6099.234 (Official Build) (x86_64)
```

I think we need multiple headers with same key.

**Comment by fakeshadow** [comment]
> But Chrome doesn't read cookies correctly. It's all malformed. First cookie with last cookie's expiration time in:
> 
> ```
> MacOS Chrome
> Version 120.0.6099.234 (Official Build) (x86_64)
> ```
> 
> I think we need multiple headers with same key.

Can you try this branch to see if it works for your use case? You can import it by adding patch session to your `Cargo.toml`
```
[patch.crates-io]
xitca-http = { git = "https://github.com/HFQR/xitca-web", rev = "d80fd7b227a0edb548f59348842d207130e818b3" }
```

**Comment by fakeshadow** [comment]
And maybe run `cargo update` after adding the patch.

**Comment by je3f0o** [comment]
I tried to replace the patch and tested. Yes it's working. I got 2 cookies in browser:
```
HTTP/1.1 200 OK
set-cookie: access_key=abc; HttpOnly; Secure; Path=/; Expires=Fri, 02 Feb 2024 02:33:50 GMT
set-cookie: refresh_key=abc; HttpOnly; Secure; Path=/; Expires=Fri, 02 Feb 2024 02:33:50 GMT
```

Btw you are so fast. Fast response and fast updates :P.

**Comment by fakeshadow** [comment]
> I tried to replace the patch and tested. Yes it's working. I got 2 cookies in browser:
> 
> ```
> HTTP/1.1 200 OK
> set-cookie: access_key=abc; HttpOnly; Secure; Path=/; Expires=Fri, 02 Feb 2024 02:33:50 GMT
> set-cookie: refresh_key=abc; HttpOnly; Secure; Path=/; Expires=Fri, 02 Feb 2024 02:33:50 GMT
> ```
> 
> Btw you are so fast. Fast response and fast updates :P

np. Thank you for bringing the issue up and I can imagine it's a deal breaker for most people using multiple set-cookie headers.
I have released `xitca-http 0.2.2` on crates.io. You can remove the patch session from your `Cargo.toml` and run `cargo update` one more time for a stable fix.

**Comment by je3f0o** [comment]
Recently I start coding web app in Rust. I tried few different frameworks based on https://www.techempower.com/benchmarks and I liked this one. But I cannot figure out one thing.
How to create an Error response in middleware?
```rs
async fn error_handler<S, C, Res>(s: &S, ctx: WebContext<'_, C>)
  -> Result<Res, Error<C>>
where S: for<'r> Service<WebContext<'r, C>, Response = Res, Error = Error<C>>,
{
  s.call(ctx).await.map_err(|err| {
    eprintln!("GOT SOME ERROR: ${err:?}");
    err
  })
}
```

For example what if i want response status 500 when panic happaned. Or what if i want modify response body based on error etc... I cannot figure out custom error handler...

**Comment by fakeshadow** [comment]
> Recently I start coding web app in Rust. I tried few different frameworks based on https://www.techempower.com/benchmarks and I liked this one. But I cannot figure out one thing. How to create an Error response in middleware?
> 
> ```rust
> async fn error_handler<S, C, Res>(s: &S, ctx: WebContext<'_, C>)
>   -> Result<Res, Error<C>>
> where S: for<'r> Service<WebContext<'r, C>, Response = Res, Error = Error<C>>,
> {
>   s.call(ctx).await.map_err(|err| {
>     eprintln!("GOT SOME ERROR: ${err:?}");
>     err
>   })
> }
> ```
> 
> For example what if i want response status 500 when panic happaned. Or what if i want modify response body based on error etc... I cannot figure out custom error handler...

You may want to give this piece of doc a read for error handling: 
https://docs.rs/xitca-web/latest/xitca_web/error/index.html

Unlike other popular web frameworks in Rust xitca-web encourages you to handle error lazily. In plain word you just return `Error<C>` type when an error occur and eventually it will be converted to a http response when needed. The conversion can either be handled by a middleware you provided or a default catch all xitca-web offers as last chance conversion.

For example of catching panic with a blank 500 error response.
```rust
use xitca_web::{
    error::{Error, Internal},
    handler::handler_service,
    http::WebResponse,
    route::get,
    service::Service,
    App, WebContext,
};

fn main() -> std::io::Result<()> {
    App::new()
        .at("/", get(handler_service(root)))
        .enclosed_fn(catch_panic)
        .serve()
        .bind("localhost:8080")?
        .run()
        .wait()
}

async fn catch_panic<S, C>(service: &S, ctx: WebContext<'_, C>) -> Result<WebResponse, Error<C>>
where
    S: for<'r> Service<WebContext<'r, C>, Response = WebResponse, Error = Error<C>>,
{
    use futures::FutureExt;
    std::panic::AssertUnwindSafe(service.call(ctx))
        .catch_unwind()
        .await
        // Internal is the default blank 500 error response type. we convert it to Error<C> type and 
        // the default catch all convertor would help up construct a http response.
        .map_err(|_| Internal)?
}

// always panic at "/" path
async fn root() -> &'static str {
    panic!("")
}
```

**Comment by fakeshadow** [comment]
For custom typed error you can reference these doc and example:
https://docs.rs/xitca-web/latest/xitca_web/error/struct.Error.html
https://github.com/HFQR/xitca-web/blob/main/examples/error-handle/src/main.rs
https://github.com/HFQR/xitca-web/blob/main/examples/macros/src/main.rs

In general `xitca-web` can use any type as error as long as it implement the traits needed presented by above doc and examples. Personally I find start with the macro offered by `codegen` feature is an easy way to get into the pattern.

**Comment by je3f0o** [comment]
Ok, thank you very much. I'm gonna close this issue now. When i got more familiar with this framework and better understand traits I will try to contribute later. Thanks again.
