### ISSUE TITLE
i saw the techempower benchmark, is it really thread per core?

### ISSUE THREAD

**Issue by ouvaa** [HFQR/xitca-web#961]
went through techempower benchmark code, saw thread per core. is this the same as glommio or monoio? i dont see anything mentioning glommio or monoio here. how does it compared with them? is it really thread per core? any benchmark to show core utilization for 24 cores and above?

thx

```
//! show case of axum running on proper thread per core server with io-uring enabled.

mod db;
mod ser;
mod util;

use std::sync::Arc;

use axum::{
    extract::{Json, Query, State},
    http::{
        header::{HeaderValue, SERVER},
        StatusCode,
    },
    response::{Html, IntoResponse, Response},
    routing::{get, Router},
};
use tower_http::set_header::SetResponseHeaderLayer;

use crate::{db::Client, ser::Num, tower_compat::TowerHttp};

fn main() -> std::io::Result<()> {
    let service = TowerHttp::service(|| async {
        let cli = db::create().await?;
```

**Comment by fakeshadow** [comment]
The "thread-per-core" xitca-web designed around is losely based on this definition:
> Thread per core combines three big ideas: (1) concurrency should be handled in userspace instead of using expensive kernel  threads, (2) I/O should be asynchronous to avoid blocking per-core threads, and (3) data is partitioned between CPU cores to eliminate synchronization cost and data movement between CPU caches. It’s hard to build high throughput systems without (1) and (2), but (3) is probably only needed on really large multicore machines.

What runtime you use does not break or make a thread-per-core design. As you can see async Rust in general is capable of the point 1 and 2. For point 3 is where a typical async Rust "work-stealing" and "thread-per-core" runtime diverge and xitca-web is not strictly in either camp and more like at middle ground. It avoid synchronization when possible but not completely. And library user can easily opt-in shared state and synchronization whenever they need it.

For specific `tokio` and `tokio-uring`(opt-in) crates are utilized as runtime implementation. As for benchmark you can use techempower as reference. It uses a 14core/28threads Xeno processor for generating it's results.

**Comment by fakeshadow** [comment]
btw in the code snippet you posted `tokio-uring` is what used as async runtime and all IO are handled by `io-uring`.

**Comment by ouvaa** [comment]
@fakeshadow ok thx for the explanations.
