### ISSUE TITLE
possible to do a http2 websocket example? current one is only http1.1

### ISSUE THREAD

**Issue by ouvaa** [HFQR/xitca-web#969]
1. pls help get this up. do also pls put up a section for sponsorship at least for us to buy u coffees. it's really good.
2. i see greater adoption with actual use case scenario (case studies/simple info of current users) and appreciation page for xitca.

if websocket http2 is available. i can put in example use case for reference with results of production run/use.

thx

**Comment by fakeshadow** [comment]
The websocket example work for http2 if you enable xitca-web's http2 crate feature. 

This project is aiming to be 100% free and we can't dedicate extra time/effort to it even with extra funding. Contributions like Issues and PRs are welcomed and it'll be the main drive force of this project.

**Comment by ouvaa** [comment]
@fakeshadow ok.
