### ISSUE TITLE
too many file descriptors. possible to do one that share 1 file descriptor? (feature request)

### ISSUE THREAD

**Issue by ouvaa** [HFQR/xitca-web#970]
everything's great but for one last area not sure if it'll be an easy update, using one file descriptor like uWebsocket:
https://unetworkingab.medium.com/5-million-http-3-requests-per-second-d8f0074a5367

can this be part of the roadmap?

```
2024-03-05T02:38:16.911057Z ERROR xitca_server::worker: Error accepting connection: Too many open files (os error 24)
2024-03-05T02:38:16.911130Z ERROR xitca_server::worker: Error accepting connection: Too many open files (os error 24)
2024-03-05T02:38:16.911130Z ERROR xitca_server::worker: Error accepting connection: Too many open files (os error 24)
2024-03-05T02:38:16.911165Z ERROR xitca_server::worker: Error accepting connection: Too many open files (os error 24)
2024-03-05T02:38:16.911169Z ERROR xitca_server::worker: Error accepting connection: Too many open files (os error 24)
```

**Comment by fakeshadow** [comment]
I don't know what you mean by that. Every TCP/UDS client connection will take up one fd and there is no way around it. http3 in xitca-web is already using a single UDP socket as listener and it's basically what defined by QUIC spec.

**Comment by fakeshadow** [comment]
If you want to enable http3 with xitca-web you can do the following:
```rust
[dependencies]
xitca-web = { version = "0.4" }
xitca-http = { version = "0.4", features = ["http3"] }
xitca-server = { version = "0.2", features = ["http3"] }

quinn = "0.10"

use quinn::ServerConfig;
use xitca_http::HttpServiceBuilder;
use xitca_server::Builder;
use xitca_web::{handler::handler_service, route::get, service::ServiceExt, App};

fn main() -> std::io::Result<()> {
    let config = http3_config();
    let app = App::new()
        .at("/", get(handler_service(root)))
        .finish()
        .enclosed(HttpServiceBuilder::new());
    Builder::new()
        .bind_h3("http/3", "127.0.0.1:8080", config, app)?
        .build()
        .wait()
}

fn http3_config() -> ServerConfig {
    todo!()
}

async fn root() -> &'static str {
    "hello,world!"
}
```
The API is not directly offered by `xitca-web` itself due to http3 is still not mature enough and the configuration and service discovery needs some attention. You can reference the `multi-http-services` example for a working application that redirect http/2 trafic to http/3

**Comment by ouvaa** [comment]
@fakeshadow yes u are right, i was wrong. thank you for the correction.

**Comment by ouvaa** [comment]
@fakeshadow ok. i hv no idea why my golang code does not need so many file descriptor. it uses so reuseport and in prefork mode. seems can support a lot more connections without increasing the file descriptors

**Comment by fakeshadow** [comment]
It's impossible to handle more fds than the process and global limit. It's likely you are not comparing the same thing.

**Comment by ouvaa** [comment]
@fakeshadow can u see this?
https://unetworkingab.medium.com/5-million-http-3-requests-per-second-d8f0074a5367
```
Regardless whether we have 1 or 10000 connections, only one single system level socket is used and so all incoming and outgoing traffic flows through one single file descriptor. This means that practically all memory overhead is in user space alone (space benchmarks will follow). It also means multiple QUIC connections can be handled with one syscall, which is not the case when having one TCP file descriptor and socket per TCP connection.
```
is it wrong?

**Comment by fakeshadow** [comment]
> @fakeshadow can u see this? https://unetworkingab.medium.com/5-million-http-3-requests-per-second-d8f0074a5367
> 
> ```
> Regardless whether we have 1 or 10000 connections, only one single system level socket is used and so all incoming and outgoing traffic flows through one single file descriptor. This means that practically all memory overhead is in user space alone (space benchmarks will follow). It also means multiple QUIC connections can be handled with one syscall, which is not the case when having one TCP file descriptor and socket per TCP connection.
> ```
> 
> is it wrong?

It's for http/3, not http/1 nor http/2. I already explained this from the first reply in this issue. quic and http/3 uses UDP as transport layer while TCP and UDS are used for http/1 and http/2 transport. 

xitca-web supports QUIC and http/3 just fine. Multiplexing over a single UDP socket is not a rich feature, it's a requirement by the QUIC spec itself.

**Comment by ouvaa** [comment]
@fakeshadow ok thx
