### ISSUE TITLE
can you show an example of Router /hello hello world text for xitca multi http2/3?

### ISSUE THREAD

**Issue by ouvaa** [HFQR/xitca-web#980]
not sure how to combine xitca-web with xitca-server

i'll try to write an example and hope you have something like
https://github.com/cloudwego/hertz-examples

in future. i can contribute examples too then.

this is how i'm doing it now:
```
async fn handler_h1(req: Request<RequestExt<h1::RequestBody>>) -> Result<Response<ResponseBody>, Infallible> {
    let path = req.uri().path();
    let response_body = if path == "/hello" {
        "Hello World from Http/1!"
    } else {
        "Not Found"
    };

    Ok(Response::builder()
        .header(CONTENT_TYPE, TEXT_UTF8)
        .body(response_body.into())
        .unwrap())

}
```

**Comment by fakeshadow** [comment]
Let's keep the talk in one issue. I'll close this one and reply to you in the other similar issue. Hope you don't mind.
