### ISSUE TITLE
how to drop a connection as fast as possible? (in the event of ddos attack)

### ISSUE THREAD

**Issue by ouvaa** [HFQR/xitca-web#982]
so now i hv 
req.body().socket_addr().to_string()

how do i drop the connection as soon as possible?

```
    let res = Response::builder()
        .status(200)
        // possible redirect browser to http/3 service.
        .header("Alt-Svc", "h3=\":443\"; ma=86400")
        .header(CONTENT_TYPE, TEXT_UTF8)
        .body(remote_addr.into())?;
    Ok(res)
    
```

what am i supposed to return? are there any documentations i can reference?

**Comment by fakeshadow** [comment]
You can send `Connection: Close` header to client to inform it the connection is about to be closed. After you sent the header xitca would go into graceful shutdown for that client connection. For http/1 it means the connection would be closed immediately. For http/2 it means the connection would be closed after all existing multiplex streams belonging to that client connection are finished. For http/3 there is no explicit way to close the connection yet.

**Comment by ouvaa** [comment]
@fakeshadow is there a way to drop the connection without informing the client? i want it discon / terminated immediately. notifying the client will encourage it to continue with the ddos

**Comment by fakeshadow** [comment]
No that's not how it works. you are misunderstanding how DDoS work. Replying and close connection does not encouraging DDoS.

**Comment by fakeshadow** [comment]
Let's put it simple. If you are rate limiting a client the only difference between immature shutdown and graceful shutdown is an extra write to socket with possibly less than a hundred bytes of data as http response. There is no amplification in any form and the cost of attack scales linearly. It also means if you fail to rate limit client's socket connection with your firewall saving these bytes write would not change anything. You will still be flooded with newly opened connections.

**Comment by ouvaa** [comment]
@fakeshadow the problem is you are advertising the site is responding, which will cause the ddos not to stop. it's better to not respond to the ddos so as that in most normal circumstances, the attack will stop.

also, will use firewall settings to block the ip instead of the program but best not to even send a byte back.

how can this be done?
