### ISSUE TITLE
Chatgpt multiple errors unexpected! 

### ISSUE THREAD

**Issue by Fay1985** [HFQR/xitca-web#990]
Check out this short exchange with Chatgpt, a series of wrong answers! 
https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fchat.openai.com%2Fshare%2Fff11de2d-19e4-4a34-a430-af008d75b7a7&data=05%7C02%7C%7Cfa0826a864e746089a7008dc4684cbbc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638462783360167390%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=H58eBySeIY64OfmYgpyfeHFD2XohQmlHUuSZNpbDl%2F0%3D&reserved=0

**Comment by fakeshadow** [comment]
Sorry the link is irrelevant to xitca-web and we don't have any influence on chatgpt nor any LLM. If you are having problem with it please contact it's support.
